language: rust
cache: cargo

rust: nightly-2018-06-01
addons:
  apt:
    packages:
      - gcc-multilib
      - libssl-dev

env:
  - TARGET=x86_64-unknown-linux-gnu
  
script:
  - cargo build --target $TARGET --release
  - file target/$TARGET/release/fondbot

before_deploy:
  - pushd target/$TARGET/release
  - tar cJf fondbot-$TARGET.tar.xz fondbot
  - popd
  - mv target/$TARGET/release/*.tar.xz .

deploy:
  provider: releases
  api_key:
    secure: P/v9YzGb8iMutd2ZWnXQi0+rqnBLgvW6jnXkeEqlOcPHffx9i0GWSoXzEhFqyI5rXXGxJQZbEkKAYW6WERSadruiLeC5APwWTvUf97xAIe6yJZtLLm99FyOKO1sA6FIjQ4bHMT9q2dPqawSg2fW75ZvDx6Pig8ajfmdBNHbl3JzJz1itLwhJRjfgMNWgzJSg/rIdLiEPAB/aP03hsjTlgRkUKTvo6/4ER5ElhkvzUbXZmiCRFdD8yfPwm2j6IR35731dSVcgvYpGwyQylrt9ZBbirdxYbjWMyVocm3/o6Va2uXqe9cm8PQLc2gI4z+l/ZaKfmiCfZjlCkMr0SmrNVssBbTk/rWLnA8AlFNuI1nMoebaVdzV51gFZJabXDUJZ8SOzfCktq+rJMPoq+nAqr+HKqEe/9B3LI84/U2atnfnwE+USHqfMBl4PpgSxbXKydlGIPqvb9TXYG49Y7kJkNK2zHABe8IEXD4FJZJIx75qQgkB87JdTAmIFsrkNZBFxlTztgOr0I9oVNnX4oJL0PtOUmxq8HQTHIiMaGir2aLTDLEkNN1MbRxmu1/rZDDIjhjfCaPTZVzXnK97BxUXR5PmzgR0UMc0rPEXSBcEuT47Dwob1ri3VaOUWvmDSVKE8q+DbSBXM3AZpsfS+OH8CPQQfd+HZrJ4jaaQyY0B+IWU=
  file_glob: false
  file: fondbot-$TARGET.tar.xz
  # don't delete the artifacts from previous phases
  skip_cleanup: true

branches:
  only:
    - master

notifications:
  email:
    on_success: always

