[package]
name = "fondbot"
version = "0.1.0"
authors = ["Shou Ya <github@lain.li>"]


[dependencies]
telegram-bot = "0.5.0"
serde = "0.8.19"
chrono = { version = "0.2", features = ["serde", "rustc-serialize"] }
serde_derive = "0.8.19"
serde_json = "*"
erased-serde = "0.1.3"
log = "*"
dotenv = "*"
env_logger = "*"
hyper = "0.9.14"
regex = "*"
lazy_static = "*"
slog = { version = "*", features = ["max_level_trace"] }
slog-scope = "*"
slog-extra = "*"
slog-term = "*"

[dependencies.clippy]
optional = true
version = "*"

[features]
lint = ["clippy"]
