[package]
name = "fondbot"
version = "0.1.0"
authors = ["Shou Ya <github@lain.li>"]


[dependencies]
telegram-bot = "0.5.0"
serde = "0.8.20"
chrono = { version = "0.2", features = ["serde", "rustc-serialize"] }
serde_derive = "0.8.20"
serde_json = "0.8.4"
serde_yaml = "0.5"
erased-serde = "0.1.3"
log = "*"
env_logger = "*"
hyper = "0.9.14"



