[package]
name = "fondbot"
version = "0.1.0"
authors = ["Shou Ya <github@lain.li>"]


[dependencies]
telegram-bot = "0.5.0"
serde = "*"
chrono = { version = "0.4.0", features = ["serde", "rustc-serialize"] }
serde_derive = "*"
serde_json = "*"
erased-serde = "0.1.3"
log = "*"
dotenv = "*"
env_logger = "*"
hyper = "0.9.14"
regex = "*"
lazy_static = "*"
slog = { version = "1.5.2", features = ["max_level_trace"] }
slog-scope = "0.2.2"
slog-extra = "0.1.2"
slog-term = "1.5.0"
diesel = { version = "0.15.0", features = ["sqlite"] }
diesel_codegen = { version = "0.15.0", features = ["sqlite"] }


[dependencies.clippy]
optional = true
version = "*"

[features]
lint = ["clippy"]
